CREATE TABLE contacts (
  id BIGINT(20) AUTO_INCREMENT PRIMARY KEY,
  company_id BIGINT(20) DEFAULT NULL,
  position VARCHAR(255) NOT NULL,
  first_name VARCHAR(255) NOT NULL,
  last_name VARCHAR(255) DEFAULT NULL,
  email VARCHAR(255) NOT NULL,
  phone_number VARCHAR(255) NOT NULL,
  notes VARCHAR(255) DEFAULT NULL,
  created_date BIGINT(20) NOT NULL,
  updated_date BIGINT(20) DEFAULT NULL
);